#!/usr/bin/env python3
"""Split a ZINC22 3D downloader script into one download script per tranche.

The CartBlanche22 tranche browser hands you a single file (e.g.
``ZINC22-downloader-3D-pdbqt.tgz.curl``) with one curl command per archive,
spanning every tranche you selected, e.g.::

    curl ... -o H04/H04M000/a/H04M000-N-aaaaaa.pdbqt.tgz https://files.docking.org/zinc22/zinc-22a/H04/H04M000/a/H04M000-N-aaaaaa.pdbqt.tgz

The pipeline works per tranche, so this groups those commands by their ZINC22
tranche code (``H<heavy atoms><M|P><logP*100>``, e.g. ``H04M000``; every
charge state of a tranche goes in the same group) and writes:

  - ``<out-dir>/<code>.curl``: that tranche's commands, wrapped so a failed
    command is counted and reported instead of silently ignored (see
    ``SCRIPT_HEADER``).
  - ``<map>``: a ``curl_script tranche`` mapping file for ``pipeline.py
    --map``.

Usage::

    python3 zinc_split.py ZINC22-downloader-3D-pdbqt.tgz.curl --out-dir zinc22_scripts --map tranches.txt
"""
from __future__ import annotations

import argparse
import os
from pathlib import Path

from io_parse import ZINC22_TRANCHE_RE

# Every generated script keeps going past a failed download (ZINC regularly
# 404s on individual archives) but counts failures and exits nonzero if any
# occurred, so `pipeline.download_tranche` can report them. The ERR trap
# fires for the last command of an `a && b` list too, so it catches
# `mkdir -p x && curl ...` style lines.
SCRIPT_HEADER = """#!/bin/bash
# Generated by zinc_split.py from {source} -- tranche {code}.
fails=0
trap 'fails=$((fails+1)); echo "FAILED (rc=$?): $BASH_COMMAND" >&2' ERR

"""

SCRIPT_FOOTER = """
echo "$fails download command(s) failed" >&2
[ "$fails" -eq 0 ]
"""


def split_downloader(lines: list[str]) -> tuple[dict[str, list[str]], list[str]]:
    """Group downloader command lines by ZINC22 tranche code.

    Returns:
        `(groups, unmatched)`: commands per tranche code in first-seen
        order, and non-blank, non-comment lines with no tranche code.
    """
    groups: dict[str, list[str]] = {}
    unmatched: list[str] = []
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = ZINC22_TRANCHE_RE.search(line)
        if not m:
            unmatched.append(line)
            continue
        groups.setdefault(m.group(0), []).append(line)
    return groups, unmatched


def split_to_files(src: Path, out_dir: Path, map_path: Path) -> dict[str, int]:
    """Split downloader `src` into `<out_dir>/<code>.curl` scripts and a `map_path` mapping file.

    Returns:
        Commands per tranche code, in file order.

    Raises:
        ValueError: If `src` is empty or contains no ZINC22 tranche codes.
    """
    text = src.read_text(errors="replace")
    if not text.strip():
        raise ValueError(f"{src.name} is empty. Download it again from CartBlanche22.")
    groups, unmatched = split_downloader(text.splitlines())
    if not groups:
        raise ValueError(f"No ZINC22 tranche codes (e.g. H04M000) found in {src.name}. Is it a ZINC22 3D downloader?")
    if unmatched:
        # Anything without a tranche code (e.g. a stray `mkdir` of a shared
        # parent directory) can't be assigned to a tranche. `curl
        # --create-dirs` makes such lines unnecessary, so they're dropped.
        print(f"Warning: skipped {len(unmatched)} line(s) with no tranche code, e.g.: {unmatched[0]}")

    out_dir.mkdir(parents=True, exist_ok=True)
    map_rows = []
    for code, cmds in groups.items():
        script = out_dir / f"{code}.curl"
        script.write_text(SCRIPT_HEADER.format(source=src.name, code=code) + "\n".join(cmds) + "\n" + SCRIPT_FOOTER)
        map_rows.append(f"{os.path.relpath(script, map_path.parent)}\t{code}")

    map_path.parent.mkdir(parents=True, exist_ok=True)
    map_path.write_text("curl_script\ttranche\n" + "\n".join(map_rows) + "\n")
    return {code: len(cmds) for code, cmds in groups.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description="Split a ZINC22 downloader script into per-tranche scripts")
    parser.add_argument("downloader", help="The .curl/.wget file from CartBlanche22")
    parser.add_argument("--out-dir", required=True, help="Directory to write per-tranche scripts into")
    parser.add_argument("--map", required=True, help="Mapping file to write, for pipeline.py --map")
    args = parser.parse_args()

    out_dir = Path(args.out_dir).expanduser().resolve()
    map_path = Path(args.map).expanduser().resolve()
    try:
        counts = split_to_files(Path(args.downloader).expanduser().resolve(), out_dir, map_path)
    except ValueError as exc:
        raise SystemExit(str(exc))

    for code, n in counts.items():
        print(f"{code}: {n} command(s) -> {out_dir / (code + '.curl')}")
    print(f"\nWrote {len(counts)} tranche script(s) and mapping file {map_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
